{% raw %}---
- name: Take the site out of  maint mode
  file: path="/usr/share/nginx/html/{{ project_name }}_offline.html" state=absent 
  become: yes
  become_user: root
  tags:
    - clean_up {% endraw %}
