{% raw %}---
- name: Install packages via pip
  pip: name={{ item }} executable=pip3
  become_user: root 
  become: true
  with_items:
    - virtualenvwrapper
  tags:
      - web
      - venv

- name: create the virtualenvwrapper dir if not present
  file: path={{ virtualenvs_dir }} owner={{ deploy_user }} state=directory
  tags:
      - web
      - venv

- name: Add virtualenvwrapper init to the bash profile
  lineinfile: dest=/home/{{ deploy_user }}/.profile line="export WORKON_HOME=~/virtualenvs"
  tags:
      - web
      - venv

- name: Set Python3 as the virtualenvwrapper python 
  lineinfile: dest=/home/{{ deploy_user }}/.profile line="export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3"
  tags:
      - web
      - venv
- name:  Init virtualenvwrapper on login
  lineinfile: dest=/home/{{ deploy_user }}/.profile line="source /usr/local/bin/virtualenvwrapper.sh"
  tags:
      - web
      - venv

- name: create the project virtualenv
  command: python3 -m venv {{ virtualenvs_dir }}/{{ project_name }}-env 
  args:
      creates: "{{ virtualenvs_dir }}/{{ project_name }}-env/bin/activate"
  tags:
      - web
      - venv

- name: update the source hg
  shell: hg pull
      && hg update
  when: vcs == 'hg'
  args:
      chdir: "{{ sites_dir }}/{{ project_name }}"
  tags:
      - venv 

- name: update the source git 
  git: repo={{ project_repo }} 
        dest={{ sites_dir }}/{{ project_name }}
  tags:
      - venv 

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenvs_dir }}/{{ project_name }}-env 
      requirements={{ sites_dir }}/{{ project_name }}/requirements/production.txt
  tags:
      - web
      - venv

- pause: prompt="Place your production settings [env.production] file in {{ keystore_path }} 
                [Enter] to continue"
  tags:
      - venv 

- name: Copy the env.production file to the project_root 
  copy: src={{ keystore_path }}/env.production
        dest={{ sites_dir }}/{{ project_name }}/.env
        owner={{ deploy_user }}
        group={{ deploy_user }}
  tags:
    - venv 

  
- name: Copy/Create the postactivate env file 
  template: src=postactivate.j2
            dest={{ virtualenvs_dir }}/{{ project_name }}-env/bin/postactivate
            owner={{ deploy_user }}
            group={{ deploy_user }}
            mode=0740
            backup=yes
  tags:
      - web
      - venv 
      - postactivate {% endraw %} 
