{% raw %}---
- name: update the apt-cache
  apt: update_cache=yes cache_valid_time=3600
  become_user: root
  become: true
  tags:
    - bower

- name: install bower and dependencies
  become_user: root
  become: true
  apt: >
        pkg={{ item }}  
        state=latest
        force=yes
  with_items:
    - nodejs 
    - npm
    - nodejs-legacy
  tags:
    - bower
    - node

- name: install bower 
  become_user: root
  become: true
  shell: npm install -g bower
  tags:
     - bower

- name: install frontend dependencies 
  shell: bower install
  args:
     chdir: "{{ sites_dir }}/{{ project_name }}"
  tags:
     - bower{% endraw %}
