{% raw %}- name: restart gunicorn 
  supervisorctl: name={{ project_name }}
                 state=restarted
  become_user: root
  become: true

- name: restart nginx
  service: name=nginx state=restarted
  become: true{% endraw %}
    

