{% raw %}---
- name: Create the application log folder
  file: path={{ sites_dir }}/{{ project_name }}/gunicorn/
        owner={{ deploy_user }}
        group={{ deploy_user }}
        state=directory
  tags:
      - gunicorn

- name: Copy/Create the gunicorn script
  template: src=gunicorn.j2
            dest={{ sites_dir }}/{{ project_name }}/gunicorn.conf
            backup=yes
  tags:
      - gunicorn

- name: Install Supervisor 
  apt: name=supervisor update_cache=yes state=latest cache_valid_time=36000
  become_user: root
  become: true
  tags:
      - packages
      - supervisor
      - gunicorn

- name: Deploy the Supervisor Script
  template: src=supervisor.j2
            dest=/etc/supervisor/conf.d/{{ project_name }}.conf
            backup=yes
  become_user: root
  become: true
  tags:
     - gunicorn
     - supervisor

- name: Ensure that supervisor is running
  service: name=supervisor state=started
  become_user: root
  become: true
  tags:
     - gunicorn
     - supervisor

- name: Re-read the Supervisor config files
  command: supervisorctl reread
  become_user: root
  become: true
  tags:
     - gunicorn
     - supervisor

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update
  become_user: root
  become: true
  notify: restart gunicorn 
  tags:
     - gunicorn
     - supervisor{% endraw %}
