{% raw %}---
- name: Install packages via pip
  pip: name={{ item }}
  become_user: root 
  become: true
  with_items:
    - virtualenv
    - virtualenvwrapper
  tags:
      - web
      - venv

- name: create the virtualenvwrapper dir if not present
  file: path={{ virtualenvs_dir }} owner={{ deploy_user }} state=directory
  tags:
      - web
      - venv

- name: Add virtualenvwrapper init to the bash profile
  lineinfile: dest=/home/{{ deploy_user }}/.profile line="export WORKON_HOME=~/virtualenvs"
  tags:
      - web
      - venv

- name: Add virtualenvwrapper init to the bash profile
  lineinfile: dest=/home/{{ deploy_user }}/.profile line="source /usr/local/bin/virtualenvwrapper.sh"
  tags:
      - web
      - venv

- name: create the project virtualenv
  command: virtualenv {{ virtualenvs_dir }}/{{ project_name }}-env --no-site-packages
  args:
      creates: "{{ virtualenvs_dir }}/{{ project_name }}-env/bin/activate"
  tags:
      - web
      - venv

- name: update the source hg
  shell: hg pull
      && hg update
  when: vcs == 'hg'
  args:
      chdir: "{{ sites_dir }}/{{ project_name }}"
  tags:
      - venv 

- name: update the source git 
  shell: git pull
  when: vcs == 'git'
  args:
      chdir: "{{ sites_dir }}/{{ project_name }}"
  tags:
      - venv 

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenvs_dir }}/{{ project_name }}-env 
      requirements={{ sites_dir }}/{{ project_name }}/requirements/production.txt
  tags:
      - web
      - venv

- pause: prompt="Copy your .env file to {{ keystore_path }} 
               [Enter] to continue"
  tags:
      - venv 

- name: Copy the .env file to the project_root 
  copy: src={{ keystore_path }}/.env
        dest={{ sites_dir }}/{{ project_name }}/.env
        owner={{ deploy_user }}
        group={{ deploy_user }}
  tags:
    - venv 

  
- name: Copy/Create the postactivate env file 
  template: src=postactivate.j2
            dest={{ virtualenvs_dir }}/{{ project_name }}-env/bin/postactivate
            owner={{ deploy_user }}
            group={{ deploy_user }}
            mode=0740
            backup=yes
  tags:
      - web
      - venv 
      - postactivate {% endraw %}
